"use client";

import { FormEvent, useState } from "react";
import { LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ApiError, FuturePlan, createFuturePlan, updateFuturePlan } from "@/lib/api";

export function FuturePlanDialog({ open, onOpenChange, projectId, plan, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; projectId: string; plan?: FuturePlan | null; onSaved: (plan: FuturePlan) => void }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); const data = new FormData(event.currentTarget); const payload = { title: String(data.get("title")).trim(), description: String(data.get("description") || "").trim() || null, target_date: String(data.get("target_date") || "") || null, ...(plan ? { status: String(data.get("status")) as FuturePlan["status"] } : {}) }; try { const saved = plan ? await updateFuturePlan(projectId, plan.id, payload) : await createFuturePlan(projectId, payload); onSaved(saved); onOpenChange(false); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "The future plan could not be saved."); } finally { setSaving(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="p-6 sm:max-w-[520px]"><DialogHeader><DialogTitle className="text-xl">{plan ? "Edit future plan" : "New future plan"}</DialogTitle><DialogDescription>Capture an idea without forcing it into this week.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="plan-title">Title</Label><Input id="plan-title" name="title" defaultValue={plan?.title ?? ""} placeholder="What might come next?" maxLength={160} required className="h-11" /></div><div className="space-y-2"><Label htmlFor="plan-description">Details</Label><Textarea id="plan-description" name="description" defaultValue={plan?.description ?? ""} placeholder="Add context, links, or next questions..." maxLength={3000} className="min-h-24" /></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label htmlFor="target-date">Target date (optional)</Label><Input id="target-date" name="target_date" type="date" defaultValue={plan?.target_date ?? ""} className="h-11" /></div>{plan ? <div className="space-y-2"><Label htmlFor="plan-status">Status</Label><select id="plan-status" name="status" defaultValue={plan.status} className="h-11 w-full rounded-lg border bg-white px-3 text-sm"><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></div> : null}</div>{error ? <p role="alert" className="rounded-xl border border-[#efd2cd] bg-[#fff7f5] px-4 py-3 text-sm text-[#99443d]">{error}</p> : null}<DialogFooter className="-mx-6 -mb-6 px-6"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving} className="bg-[#173b35] text-white">{saving ? <LoaderCircle className="animate-spin" /> : null}{saving ? "Saving..." : "Save plan"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
